### PR TITLE
allow setting user, pass, server from environment variables

### LINKED ISSUE #3: allow artifactory-server to be specified in the config file
instead of passing server via artifactory server or even username and password from cli.

allow me to write in the config file. Perhaps even allow me to provide username and password via environment variables?

### PR DESCRIPTION
**Pull request by Jetersen**
fixes #3

### CODE REVIEW

**Comment by casz** [comment]
easy win 💯

**Comment by casz** [comment]
@Tim55667757 @nikolasj would appreciate a review 🙇

**Comment by nikolasj** [comment]
@Jetersen Hello! Thanks for the pull request.
I am going to watch them on the weekend

**Comment by Jetersen** [comment]
Much appreciated @nikolasj 🙇

**Comment by allburov** [comment]
@Tim55667757 LGTM, we could pull it.

**Comment by MindaugasLaganeckas** [comment]
It is a very nice and needed feature! Please, consider merging. @Jetersen: thanks so much for the great work! :smile:

**Comment by Tim55667757** [comment]
jokers :)))

**Pull request merged**
